name: Merge upstream branches
on:
  workflow_dispatch:
  schedule:
    - cron:  '10 */6 * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Merge upstream
        run: |
          git config --global user.name 'beuzer'
          git config --global user.email 'beuzer@users.noreply.github.com'

          git remote add upstream https://github.com/Chanzhaoyu/chatgpt-web.git
          git fetch upstream

          git checkout main
          git merge --no-edit upstream/main
          git push origin main
